export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';
export const SET_USERS_COUNT = 'SET_USERS_COUNT';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SET_ALL_COURSES = 'SET_ALL_COURSES';
